FROM gvenzl/oracle-xe:21.3.0

LABEL maintainer="Simeon Liniger <simeon.liniger@hftm.ch>"

ENV ORACLE_PASSWORD=hftadmin

ADD hftm-setup-pdb/01_setup_users.sql /container-entrypoint-initdb.d/
ADD hftm-setup-pdb/02_emp-dept_tables.sql /container-entrypoint-initdb.d/
ADD hftm-setup-pdb/03_emp-dept_data.sql /container-entrypoint-initdb.d/
ADD hftm-setup-pdb/04_verein_tables.sql /container-entrypoint-initdb.d/
ADD hftm-setup-pdb/05_verein_data.sql /container-entrypoint-initdb.d/
