-- ***********************************************************
--  Übungsdatenbank Vereinsverwaltung
--  Erweitert die Datenbank um 400 Anlässe
-- ***********************************************************
-- Im Schema von Vereinuser
ALTER SESSION SET CURRENT_SCHEMA = vereinuser;

INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (100, 'System Star So-Event', 'Grenchen', to_date('10/6/2014','MM/DD/YYYY'), 333);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (101, 'Edwards-Event', 'Zürich', to_date('4/14/2016','MM/DD/YYYY'), 516);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (102, 'Wells + Wade-Event', 'Zürich', to_date('11/7/2016','MM/DD/YYYY'), 694);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (103, 'The Network Ch-Event', 'Bern', to_date('6/21/2016','MM/DD/YYYY'), 743);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (104, 'Gallenkamp-Event', 'Bern', to_date('2/22/2017','MM/DD/YYYY'), 260);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (105, 'Cavages-Event', 'Lausanne', to_date('1/4/2015','MM/DD/YYYY'), 406);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (106, 'Krauses Sofa F-Event', 'Lausanne', to_date('12/26/2015','MM/DD/YYYY'), 411);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (107, 'Sun Television-Event', 'Genf', to_date('5/11/2015','MM/DD/YYYY'), 234);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (108, 'Merrymaking-Event', 'Luzern', to_date('7/2/2015','MM/DD/YYYY'), 673);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (109, 'Mikrotechnic-Event', 'Biel/Bienne', to_date('9/20/2015','MM/DD/YYYY'), 620);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (110, 'Franks Nurser-Event', 'St. Gallen', to_date('9/11/2017','MM/DD/YYYY'), 722);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (111, 'Joshua Doore-Event', 'Neuburg', to_date('6/26/2017','MM/DD/YYYY'), 407);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (112, 'Angels-Event', 'Waldstatt', to_date('10/19/2015','MM/DD/YYYY'), 852);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (113, 'Solution Answe-Event', 'Grenchen', to_date('2/19/2016','MM/DD/YYYY'), 830);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (114, 'Ginos Hamburg-Event', 'Grenchen', to_date('6/12/2015','MM/DD/YYYY'), 782);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (115, 'Yesterdays Re-Event', 'Grenchen', to_date('2/7/2016','MM/DD/YYYY'), 477);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (116, 'ABC Markets-Event', 'Grenchen', to_date('5/5/2015','MM/DD/YYYY'), 778);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (117, 'Laura Ashley-Event', 'Zürich', to_date('4/7/2015','MM/DD/YYYY'), 378);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (118, 'Silo-Event', 'Zürich', to_date('7/12/2017','MM/DD/YYYY'), 470);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (119, 'Atlas Architec-Event', 'Bern', to_date('11/8/2017','MM/DD/YYYY'), 566);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (120, 'Wealthy Ideas-Event', 'Bern', to_date('6/18/2015','MM/DD/YYYY'), 889);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (121, 'Dave Cooks-Event', 'Grenchen', to_date('1/7/2017','MM/DD/YYYY'), 254);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (122, 'Gas Depot-Event', 'Lausanne', to_date('4/3/2014','MM/DD/YYYY'), 344);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (123, 'Terra-Event', 'Genf', to_date('4/27/2017','MM/DD/YYYY'), 633);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (124, 'Vari-Tec-Event', 'Grenchen', to_date('10/14/2015','MM/DD/YYYY'), 333);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (125, 'Skaggs-Alpha B-Event', 'Biel/Bienne', to_date('7/29/2014','MM/DD/YYYY'), 601);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (126, 'Total Quality-Event', 'St. Gallen', to_date('9/26/2015','MM/DD/YYYY'), 829);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (127, 'Universal Desi-Event', 'Thônex', to_date('10/13/2017','MM/DD/YYYY'), 350);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (128, 'Solution Bridg-Event', 'St. Gallen', to_date('11/9/2015','MM/DD/YYYY'), 825);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (129, 'John Plain-Event', 'Les Collons', to_date('10/13/2015','MM/DD/YYYY'), 743);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (130, 'Superior Inter-Event', 'Villars-Tiercelin', to_date('11/13/2015','MM/DD/YYYY'), 495);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (131, 'Asian Junction-Event', 'Grenchen', to_date('10/29/2017','MM/DD/YYYY'), 235);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (132, 'Budget Power-Event', 'Zürich', to_date('12/14/2014','MM/DD/YYYY'), 221);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (133, 'Cavages-Event', 'Zürich', to_date('2/2/2014','MM/DD/YYYY'), 697);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (134, 'The White Rabb-Event', 'Zürich', to_date('7/4/2014','MM/DD/YYYY'), 530);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (135, 'Alladins Lamp-Event', 'Grenchen', to_date('8/20/2015','MM/DD/YYYY'), 240);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (136, 'Hill-Behan-Event', 'Bern', to_date('6/11/2015','MM/DD/YYYY'), 684);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (137, 'New World-Event', 'Lausanne', to_date('6/13/2017','MM/DD/YYYY'), 897);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (138, 'Weingartens-Event', 'Lausanne', to_date('11/8/2015','MM/DD/YYYY'), 840);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (139, 'Hills Supermar-Event', 'Genf', to_date('8/9/2016','MM/DD/YYYY'), 721);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (140, 'Music Den-Event', 'Luzern', to_date('10/15/2014','MM/DD/YYYY'), 457);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (141, 'Harvest Foods-Event', 'Biel/Bienne', to_date('2/13/2017','MM/DD/YYYY'), 904);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (142, 'Afforda-Event', 'St. Gallen', to_date('11/24/2015','MM/DD/YYYY'), 459);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (143, 'Laneco-Event', 'Grenchen', to_date('12/31/2013','MM/DD/YYYY'), 543);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (144, 'Forth + Towne-Event', 'Grenchen', to_date('9/10/2016','MM/DD/YYYY'), 296);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (145, 'Specialty Rest-Event', 'Grenchen', to_date('1/17/2014','MM/DD/YYYY'), 342);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (146, 'Libera-Event', 'Grenchen', to_date('4/28/2015','MM/DD/YYYY'), 638);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (147, 'Red Bears Tave-Event', 'Grenchen', to_date('10/11/2015','MM/DD/YYYY'), 433);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (148, 'Parts America-Event', 'Grenchen', to_date('12/25/2013','MM/DD/YYYY'), 693);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (149, 'Roadhouse Gril-Event', 'Zürich', to_date('10/20/2016','MM/DD/YYYY'), 786);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (150, 'Showbiz Pizza -Event', 'Zürich', to_date('12/16/2014','MM/DD/YYYY'), 338);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (151, 'Weingartens-Event', 'Bern', to_date('2/8/2015','MM/DD/YYYY'), 651);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (152, 'Integra Invest-Event', 'Bern', to_date('2/17/2015','MM/DD/YYYY'), 765);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (153, 'Multi Tech Dev-Event', 'Lausanne', to_date('11/24/2014','MM/DD/YYYY'), 408);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (154, 'Realty Solutio-Event', 'Lausanne', to_date('1/18/2017','MM/DD/YYYY'), 860);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (155, 'd.e.m.o.-Event', 'Genf', to_date('8/3/2015','MM/DD/YYYY'), 463);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (156, 'Gold Medal-Event', 'Luzern', to_date('10/9/2014','MM/DD/YYYY'), 483);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (157, 'Rack N Sack-Event', 'Biel/Bienne', to_date('1/23/2015','MM/DD/YYYY'), 201);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (158, 'Flexus-Event', 'Grenchen', to_date('3/5/2016','MM/DD/YYYY'), 758);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (159, 'The Flying Hip-Event', 'Barberêche', to_date('3/10/2015','MM/DD/YYYY'), 528);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (160, 'The Spotted Co-Event', 'Zürich', to_date('8/21/2014','MM/DD/YYYY'), 841);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (161, 'Specialty Rest-Event', 'Gisikon', to_date('12/23/2013','MM/DD/YYYY'), 542);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (162, 'Colonial Store-Event', 'Noville', to_date('9/5/2017','MM/DD/YYYY'), 545);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (163, 'Brilliant Home-Event', 'Grenchen', to_date('8/20/2017','MM/DD/YYYY'), 637);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (164, 'Omni Realty-Event', 'Pagnoncini', to_date('10/16/2016','MM/DD/YYYY'), 312);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (165, 'Gas Zone-Event', 'Grenchen', to_date('12/12/2014','MM/DD/YYYY'), 839);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (166, 'Farmer Jack-Event', 'Vollenweid', to_date('5/17/2016','MM/DD/YYYY'), 486);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (167, 'Mr. Clarks Ap-Event', 'Escholzmatt', to_date('12/14/2014','MM/DD/YYYY'), 400);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (168, 'Crazy Tiger-Event', 'Bern', to_date('8/23/2017','MM/DD/YYYY'), 411);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (169, 'Signa Air-Event', 'Zürich', to_date('9/30/2015','MM/DD/YYYY'), 423);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (170, 'Vinyl Fever-Event', 'Zürich', to_date('12/13/2015','MM/DD/YYYY'), 883);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (171, 'Quality Event -Event', 'Zürich', to_date('4/26/2015','MM/DD/YYYY'), 642);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (172, 'Electronics So-Event', 'Grenchen', to_date('4/13/2017','MM/DD/YYYY'), 914);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (173, 'Monmax-Event', 'Grenchen', to_date('5/19/2017','MM/DD/YYYY'), 243);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (174, 'Witmark-Event', 'Grenchen', to_date('10/3/2017','MM/DD/YYYY'), 698);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (175, 'Adaptas-Event', 'Grenchen', to_date('8/14/2017','MM/DD/YYYY'), 392);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (176, 'Anderson-Littl-Event', 'Grenchen', to_date('4/5/2016','MM/DD/YYYY'), 275);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (177, 'Flexus-Event', 'Luzern', to_date('6/10/2014','MM/DD/YYYY'), 266);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (178, 'Payless Cashwa-Event', 'Biel/Bienne', to_date('3/22/2015','MM/DD/YYYY'), 699);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (179, 'Compact Disc C-Event', 'St. Gallen', to_date('5/6/2017','MM/DD/YYYY'), 622);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (180, 'Piccolo Mondo-Event', 'Montagnon', to_date('8/3/2015','MM/DD/YYYY'), 900);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (181, 'Afforda Mercha-Event', 'Schwyz', to_date('5/25/2015','MM/DD/YYYY'), 551);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (182, 'Asian Junction-Event', 'Tegna', to_date('9/11/2016','MM/DD/YYYY'), 247);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (183, 'Oles-Event', 'Wiezikon', to_date('11/7/2017','MM/DD/YYYY'), 515);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (184, 'Sports Unlimit-Event', 'Grenchen', to_date('3/5/2015','MM/DD/YYYY'), 771);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (185, 'J. Riggings-Event', 'Hemishofen', to_date('3/27/2016','MM/DD/YYYY'), 301);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (186, 'Nobil-Event', 'Aire', to_date('3/30/2016','MM/DD/YYYY'), 271);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (187, 'Planet Pizza-Event', 'Zürich', to_date('7/19/2016','MM/DD/YYYY'), 893);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (188, 'Courtesy Hardw-Event', 'Grenchen', to_date('7/21/2017','MM/DD/YYYY'), 847);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (189, 'Best Products-Event', 'Zürich', to_date('12/15/2014','MM/DD/YYYY'), 855);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (190, 'The Jolly Farm-Event', 'Bern', to_date('3/14/2015','MM/DD/YYYY'), 227);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (191, 'Grand Union-Event', 'Grenchen', to_date('9/6/2015','MM/DD/YYYY'), 527);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (192, 'Wealthy Ideas-Event', 'Lausanne', to_date('3/12/2014','MM/DD/YYYY'), 704);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (193, 'Holly Tree Inn-Event', 'Lausanne', to_date('8/10/2015','MM/DD/YYYY'), 829);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (194, 'Market Basket-Event', 'Genf', to_date('8/30/2015','MM/DD/YYYY'), 776);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (195, 'Matrix Interio-Event', 'Luzern', to_date('12/21/2016','MM/DD/YYYY'), 611);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (196, 'Handy Andy-Event', 'Biel/Bienne', to_date('5/9/2015','MM/DD/YYYY'), 599);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (197, 'Erols-Event', 'St. Gallen', to_date('9/21/2017','MM/DD/YYYY'), 545);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (198, 'Shoe Town-Event', 'St. Gallen', to_date('3/22/2015','MM/DD/YYYY'), 541);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (199, 'Smittys Marke-Event', 'Grenchen', to_date('5/9/2014','MM/DD/YYYY'), 402);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (200, 'Erb Lumber-Event', 'Grenchen', to_date('3/2/2016','MM/DD/YYYY'), 787);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (201, 'Bonanza Produc-Event', 'Fionnay', to_date('6/23/2016','MM/DD/YYYY'), 882);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (202, 'Service Mercha-Event', 'Selzach', to_date('11/27/2016','MM/DD/YYYY'), 521);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (203, 'Access Asia-Event', 'Altishofen', to_date('12/3/2015','MM/DD/YYYY'), 813);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (204, 'Full Color-Event', 'Mettmenstetten', to_date('4/3/2016','MM/DD/YYYY'), 368);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (205, 'Rack N Sack-Event', 'Dietwilschyne', to_date('2/22/2015','MM/DD/YYYY'), 376);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (206, 'id Boutiques-Event', 'Bretzwil', to_date('8/10/2014','MM/DD/YYYY'), 537);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (207, 'Total Network -Event', 'Grenchen', to_date('7/18/2017','MM/DD/YYYY'), 783);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (208, 'Second Time Ar-Event', 'Zürich', to_date('2/3/2015','MM/DD/YYYY'), 210);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (209, 'Brand Names-Event', 'Zürich', to_date('12/21/2013','MM/DD/YYYY'), 702);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (210, 'Child World-Event', 'Zürich', to_date('5/8/2015','MM/DD/YYYY'), 708);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (211, 'Gantos-Event', 'Bern', to_date('11/20/2016','MM/DD/YYYY'), 920);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (212, 'EXPO Design Ce-Event', 'Bern', to_date('2/27/2015','MM/DD/YYYY'), 851);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (213, 'Auto Works-Event', 'Lausanne', to_date('8/21/2017','MM/DD/YYYY'), 709);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (214, 'Laura Ashley-Event', 'Grenchen', to_date('9/12/2015','MM/DD/YYYY'), 749);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (215, 'J. B. Van Sciv-Event', 'Grenchen', to_date('9/7/2016','MM/DD/YYYY'), 786);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (216, 'Magik Gray-Event', 'Grenchen', to_date('9/8/2016','MM/DD/YYYY'), 430);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (217, 'Newmark + Lewi-Event', 'Grenchen', to_date('12/7/2016','MM/DD/YYYY'), 232);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (218, 'Dun Rite Lawn -Event', 'Grenchen', to_date('1/5/2017','MM/DD/YYYY'), 886);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (219, 'Foxmoor-Event', 'Grenchen', to_date('8/4/2016','MM/DD/YYYY'), 789);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (220, 'Custom Lawn Ca-Event', 'Grenchen', to_date('8/15/2017','MM/DD/YYYY'), 890);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (221, 'New World Real-Event', 'Grenchen', to_date('9/1/2015','MM/DD/YYYY'), 396);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (222, 'Mr. Steak-Event', 'Grenchen', to_date('12/21/2016','MM/DD/YYYY'), 881);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (223, 'Endicott Shoes-Event', 'Magnedens', to_date('10/11/2017','MM/DD/YYYY'), 260);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (224, 'Exact Solution-Event', 'Bichwil', to_date('10/7/2014','MM/DD/YYYY'), 688);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (225, 'Pro Garden Man-Event', 'Les Pommerats', to_date('3/14/2016','MM/DD/YYYY'), 701);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (226, 'Consumers and -Event', 'Zürich', to_date('8/6/2015','MM/DD/YYYY'), 918);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (227, 'Handy City-Event', 'Zürich', to_date('10/8/2015','MM/DD/YYYY'), 325);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (228, 'Gemco-Event', 'Zürich', to_date('11/22/2014','MM/DD/YYYY'), 364);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (229, 'Enviro Archite-Event', 'Grenchen', to_date('11/22/2016','MM/DD/YYYY'), 312);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (230, 'Mode ODay-Event', 'Grenchen', to_date('9/9/2016','MM/DD/YYYY'), 683);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (231, 'Cala Foods-Event', 'Grenchen', to_date('10/7/2015','MM/DD/YYYY'), 735);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (232, 'EnviroSource D-Event', 'Grenchen', to_date('8/3/2014','MM/DD/YYYY'), 529);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (233, 'Forth + Towne-Event', 'Grenchen', to_date('8/1/2015','MM/DD/YYYY'), 536);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (234, 'Great Western-Event', 'Grenchen', to_date('4/2/2016','MM/DD/YYYY'), 868);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (235, 'Sistemos-Event', 'Grenchen', to_date('11/10/2017','MM/DD/YYYY'), 452);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (236, 'Todays Man-Event', 'Grenchen', to_date('12/5/2017','MM/DD/YYYY'), 471);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (237, 'Architectural -Event', 'Grenchen', to_date('9/9/2014','MM/DD/YYYY'), 494);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (238, 'DGS HomeSource-Event', 'Grenchen', to_date('8/20/2015','MM/DD/YYYY'), 570);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (239, 'Two Pesos-Event', 'Grenchen', to_date('2/11/2015','MM/DD/YYYY'), 208);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (240, 'Buck Alley Lum-Event', 'Grenchen', to_date('1/27/2014','MM/DD/YYYY'), 675);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (241, 'Kessel Food Ma-Event', 'Grenchen', to_date('8/28/2017','MM/DD/YYYY'), 218);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (242, 'Maxi-Tech-Event', 'Willisdorf', to_date('7/20/2014','MM/DD/YYYY'), 804);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (243, 'Freedom Map-Event', 'Fregiécourt', to_date('11/7/2015','MM/DD/YYYY'), 542);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (244, 'The Serendipit-Event', 'Zürich', to_date('1/13/2016','MM/DD/YYYY'), 232);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (245, 'Terra-Event', 'Zürich', to_date('6/10/2014','MM/DD/YYYY'), 493);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (246, 'Monk Home Fund-Event', 'Zürich', to_date('6/2/2015','MM/DD/YYYY'), 858);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (247, 'The Record Sho-Event', 'Bern', to_date('10/7/2015','MM/DD/YYYY'), 312);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (248, 'Strength Gurus-Event', 'Bern', to_date('3/29/2015','MM/DD/YYYY'), 587);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (249, 'JasmineSola-Event', 'Grenchen', to_date('4/6/2014','MM/DD/YYYY'), 496);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (250, 'LoRay-Event', 'Grenchen', to_date('7/29/2015','MM/DD/YYYY'), 265);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (251, 'Wealth Zone Gr-Event', 'Grenchen', to_date('6/28/2015','MM/DD/YYYY'), 414);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (252, 'Best Biz Survi-Event', 'Grenchen', to_date('7/2/2014','MM/DD/YYYY'), 248);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (253, 'Strategy Plann-Event', 'Grenchen', to_date('9/7/2015','MM/DD/YYYY'), 628);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (254, 'Planetbiz-Event', 'Grenchen', to_date('10/14/2014','MM/DD/YYYY'), 728);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (255, 'Hit or Miss-Event', 'Grenchen', to_date('6/22/2016','MM/DD/YYYY'), 708);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (256, 'Foot Quarters-Event', 'Grenchen', to_date('2/2/2014','MM/DD/YYYY'), 895);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (257, 'Corpbay-Event', 'Grenchen', to_date('5/2/2015','MM/DD/YYYY'), 458);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (258, 'Erlebachers-Event', 'Grenchen', to_date('12/11/2014','MM/DD/YYYY'), 709);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (259, 'Personal + Cor-Event', 'Ober Ottikon', to_date('7/2/2016','MM/DD/YYYY'), 899);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (260, 'Jafco-Event', 'Rickenbach', to_date('2/6/2017','MM/DD/YYYY'), 625);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (261, 'Cougar Investm-Event', 'Ilfis', to_date('5/16/2014','MM/DD/YYYY'), 316);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (262, 'Budget Power-Event', 'Zürich', to_date('11/14/2017','MM/DD/YYYY'), 903);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (263, 'Robert Hall-Event', 'Zürich', to_date('8/28/2015','MM/DD/YYYY'), 453);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (264, 'Reliable Guida-Event', 'Zürich', to_date('3/24/2015','MM/DD/YYYY'), 528);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (265, 'Desmonds Forma-Event', 'Bern', to_date('3/14/2017','MM/DD/YYYY'), 589);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (266, 'Fedco-Event', 'Bern', to_date('6/8/2015','MM/DD/YYYY'), 300);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (267, 'La Petite Boul-Event', 'Lausanne', to_date('11/11/2016','MM/DD/YYYY'), 907);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (268, 'Farrells Ice -Event', 'Grenchen', to_date('7/31/2015','MM/DD/YYYY'), 750);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (269, 'Franklin Simon-Event', 'Grenchen', to_date('10/12/2015','MM/DD/YYYY'), 884);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (270, 'Luskins-Event', 'Grenchen', to_date('2/12/2017','MM/DD/YYYY'), 717);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (271, 'Kash n Karry-Event', 'Grenchen', to_date('1/3/2017','MM/DD/YYYY'), 744);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (272, 'Albers Super M-Event', 'Grenchen', to_date('1/18/2017','MM/DD/YYYY'), 846);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (273, 'Big Daddys Re-Event', 'Grenchen', to_date('2/17/2015','MM/DD/YYYY'), 495);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (274, 'Music Boutique-Event', 'Grenchen', to_date('1/2/2017','MM/DD/YYYY'), 503);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (275, 'Red Food-Event', 'Grenchen', to_date('3/25/2015','MM/DD/YYYY'), 471);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (276, 'Rinks-Event', 'Grenchen', to_date('11/23/2016','MM/DD/YYYY'), 671);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (277, 'Finast-Event', 'Blumenstein', to_date('2/6/2015','MM/DD/YYYY'), 894);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (278, 'Multicerv-Event', 'Middes', to_date('3/21/2015','MM/DD/YYYY'), 535);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (279, 'Egghead Softwa-Event', 'Grenchen', to_date('4/14/2015','MM/DD/YYYY'), 459);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (280, 'Omni Realty-Event', 'Grenchen', to_date('11/29/2015','MM/DD/YYYY'), 475);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (281, 'Disc Jockey-Event', 'Grenchen', to_date('4/27/2014','MM/DD/YYYY'), 392);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (282, 'Brilliant Home-Event', 'Grenchen', to_date('12/14/2015','MM/DD/YYYY'), 383);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (283, 'Atlas Realty-Event', 'Grenchen', to_date('2/4/2017','MM/DD/YYYY'), 362);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (284, 'Heslops-Event', 'Grenchen', to_date('10/29/2017','MM/DD/YYYY'), 731);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (285, 'Tianguis-Event', 'Grenchen', to_date('3/18/2014','MM/DD/YYYY'), 899);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (286, 'Omni Superstor-Event', 'Grenchen', to_date('9/8/2016','MM/DD/YYYY'), 522);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (287, 'Brown Derby-Event', 'Grenchen', to_date('10/12/2016','MM/DD/YYYY'), 475);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (288, 'Flagg Bros. Sh-Event', 'Grenchen', to_date('1/5/2016','MM/DD/YYYY'), 516);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (289, 'Geris Hamburg-Event', 'Grenchen', to_date('2/17/2017','MM/DD/YYYY'), 339);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (290, 'Sofa Express-Event', 'Grenchen', to_date('2/23/2015','MM/DD/YYYY'), 451);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (291, 'Hermans World-Event', 'Grenchen', to_date('12/22/2013','MM/DD/YYYY'), 286);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (292, 'Rivera Propert-Event', 'Grenchen', to_date('7/27/2016','MM/DD/YYYY'), 785);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (293, 'Magna Consulti-Event', 'Grenchen', to_date('10/9/2016','MM/DD/YYYY'), 201);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (294, 'Dun Rite Lawn -Event', 'Grenchen', to_date('5/2/2015','MM/DD/YYYY'), 902);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (295, 'Universo Realt-Event', 'La Tour-de-Trême', to_date('1/7/2017','MM/DD/YYYY'), 921);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (296, 'Yesterdays Re-Event', 'Grenchen', to_date('3/25/2016','MM/DD/YYYY'), 678);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (297, 'Museum Company-Event', 'Grenchen', to_date('7/1/2015','MM/DD/YYYY'), 399);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (298, 'Stop N Shop-Event', 'Grenchen', to_date('8/1/2015','MM/DD/YYYY'), 831);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (299, 'Infinite Wealt-Event', 'Grenchen', to_date('7/26/2015','MM/DD/YYYY'), 326);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (300, 'Morville-Event', 'Grenchen', to_date('8/22/2017','MM/DD/YYYY'), 254);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (301, 'Lechmere-Event', 'Grenchen', to_date('5/7/2015','MM/DD/YYYY'), 480);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (302, 'Highland Appli-Event', 'Grenchen', to_date('5/3/2014','MM/DD/YYYY'), 869);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (303, 'De-Jaiz Mens C-Event', 'Grenchen', to_date('5/11/2014','MM/DD/YYYY'), 359);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (304, 'Nutri G-Event', 'Grenchen', to_date('6/8/2017','MM/DD/YYYY'), 538);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (305, 'Peter Reeves-Event', 'Grenchen', to_date('1/8/2015','MM/DD/YYYY'), 276);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (306, 'Mikro Designs-Event', 'Grenchen', to_date('3/30/2015','MM/DD/YYYY'), 850);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (307, 'Monit-Event', 'Grenchen', to_date('11/29/2014','MM/DD/YYYY'), 826);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (308, 'Silo-Event', 'Grenchen', to_date('10/27/2014','MM/DD/YYYY'), 646);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (309, 'Hills Supermar-Event', 'Grenchen', to_date('2/19/2015','MM/DD/YYYY'), 883);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (310, 'VitaGrey-Event', 'Grenchen', to_date('1/29/2017','MM/DD/YYYY'), 218);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (311, 'Circuit Design-Event', 'St. Gallen', to_date('11/29/2015','MM/DD/YYYY'), 804);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (312, 'Avant Garde Ap-Event', 'Isenfluh', to_date('6/8/2015','MM/DD/YYYY'), 256);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (313, 'Montanas Cook-Event', 'Rossinière', to_date('11/28/2015','MM/DD/YYYY'), 365);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (314, 'Specialty Rest-Event', 'Biel/Bienne', to_date('11/2/2016','MM/DD/YYYY'), 418);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (315, 'Block Distribu-Event', 'Rietli', to_date('11/13/2014','MM/DD/YYYY'), 747);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (316, 'Linens n Thin-Event', 'Regensdorf', to_date('7/17/2017','MM/DD/YYYY'), 384);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (317, 'Belle Ladi-Event', 'Mollis', to_date('10/12/2014','MM/DD/YYYY'), 774);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (318, 'Stop and Shop-Event', 'Corjolens', to_date('4/6/2015','MM/DD/YYYY'), 583);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (319, 'Thorofare-Event', 'Zürich', to_date('4/30/2015','MM/DD/YYYY'), 387);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (320, 'The Warner Bro-Event', 'Grenchen', to_date('4/3/2015','MM/DD/YYYY'), 442);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (321, 'Morville-Event', 'Grenchen', to_date('4/16/2015','MM/DD/YYYY'), 422);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (322, 'Magna Gases-Event', 'Grenchen', to_date('2/17/2014','MM/DD/YYYY'), 729);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (323, 'Leos Stereo-Event', 'Grenchen', to_date('2/11/2017','MM/DD/YYYY'), 386);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (324, 'Earthworks Yar-Event', 'Grenchen', to_date('10/28/2016','MM/DD/YYYY'), 680);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (325, 'Waccamaws Hom-Event', 'Grenchen', to_date('6/17/2017','MM/DD/YYYY'), 232);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (326, 'Parts and Piec-Event', 'Grenchen', to_date('3/3/2014','MM/DD/YYYY'), 767);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (327, 'Cherry + Webb-Event', 'Grenchen', to_date('9/3/2014','MM/DD/YYYY'), 747);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (328, 'Garden Master-Event', 'Grenchen', to_date('7/17/2015','MM/DD/YYYY'), 602);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (329, 'Bumper to Bump-Event', 'Grenchen', to_date('4/28/2017','MM/DD/YYYY'), 688);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (330, 'Coconuts-Event', 'Grenchen', to_date('9/7/2015','MM/DD/YYYY'), 621);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (331, 'Pleasures and -Event', 'Grenchen', to_date('8/24/2016','MM/DD/YYYY'), 310);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (332, 'Steve + Barry-Event', 'Grenchen', to_date('11/13/2017','MM/DD/YYYY'), 397);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (333, 'Destiny Realty-Event', 'Grenchen', to_date('9/12/2016','MM/DD/YYYY'), 405);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (334, 'Kragen Auto Pa-Event', 'Grenchen', to_date('7/6/2017','MM/DD/YYYY'), 564);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (335, 'Helping Hand-Event', 'Geristein', to_date('3/17/2016','MM/DD/YYYY'), 915);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (336, 'Waves Music-Event', 'Laufen-Uhwiesen', to_date('5/1/2017','MM/DD/YYYY'), 767);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (337, 'Larrys Market-Event', 'Grenchen', to_date('6/20/2014','MM/DD/YYYY'), 663);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (338, 'CompuAdd-Event', 'Grenchen', to_date('1/27/2014','MM/DD/YYYY'), 822);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (339, 'Asian Solution-Event', 'Grenchen', to_date('12/24/2016','MM/DD/YYYY'), 851);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (340, 'Grand Union-Event', 'Grenchen', to_date('5/23/2015','MM/DD/YYYY'), 405);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (341, 'Jeans Unlimite-Event', 'Grenchen', to_date('7/26/2015','MM/DD/YYYY'), 600);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (342, 'Simple Solutio-Event', 'Grenchen', to_date('11/30/2014','MM/DD/YYYY'), 497);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (343, 'Sounds of Soul-Event', 'Grenchen', to_date('8/5/2017','MM/DD/YYYY'), 266);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (344, 'Mervyns-Event', 'Grenchen', to_date('10/12/2014','MM/DD/YYYY'), 366);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (345, 'Gottschalks-Event', 'Grenchen', to_date('2/21/2017','MM/DD/YYYY'), 863);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (346, 'Grand Union-Event', 'Grenchen', to_date('4/21/2016','MM/DD/YYYY'), 382);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (347, 'Price Savers-Event', 'Grenchen', to_date('6/21/2015','MM/DD/YYYY'), 689);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (348, 'Casa Bonita-Event', 'Grenchen', to_date('7/18/2015','MM/DD/YYYY'), 892);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (349, 'Netstars Matri-Event', 'Grenchen', to_date('2/2/2014','MM/DD/YYYY'), 676);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (350, 'Four Leaf Clov-Event', 'Grenchen', to_date('4/20/2014','MM/DD/YYYY'), 395);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (351, 'Kents-Event', 'Grenchen', to_date('12/23/2016','MM/DD/YYYY'), 426);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (352, 'Simple Solutio-Event', 'Grenchen', to_date('2/17/2015','MM/DD/YYYY'), 895);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (353, 'Fresh Start-Event', 'Au', to_date('10/13/2014','MM/DD/YYYY'), 332);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (354, 'Magik Lamp-Event', 'Constantine', to_date('3/24/2016','MM/DD/YYYY'), 744);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (355, 'Powerbod-Event', 'Zürich', to_date('11/20/2014','MM/DD/YYYY'), 583);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (356, 'Strawberries-Event', 'Zürich', to_date('3/8/2014','MM/DD/YYYY'), 393);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (357, 'ManCharm-Event', 'Grenchen', to_date('3/11/2015','MM/DD/YYYY'), 380);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (358, 'Country Club M-Event', 'Grenchen', to_date('3/23/2014','MM/DD/YYYY'), 578);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (359, 'On Cue-Event', 'Grenchen', to_date('1/11/2014','MM/DD/YYYY'), 866);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (360, 'Dreamscape Gar-Event', 'Grenchen', to_date('7/13/2015','MM/DD/YYYY'), 845);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (361, 'William Wanama-Event', 'Grenchen', to_date('3/3/2016','MM/DD/YYYY'), 443);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (362, 'Britches of Ge-Event', 'Grenchen', to_date('4/1/2017','MM/DD/YYYY'), 776);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (363, 'Town and Count-Event', 'Grenchen', to_date('12/22/2016','MM/DD/YYYY'), 488);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (364, 'Mighty Caseys-Event', 'Grenchen', to_date('3/6/2016','MM/DD/YYYY'), 797);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (365, 'Warner Brother-Event', 'Grenchen', to_date('5/3/2017','MM/DD/YYYY'), 648);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (366, 'Terra Nova Gar-Event', 'Grenchen', to_date('7/13/2017','MM/DD/YYYY'), 726);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (367, 'Egghead Softwa-Event', 'Grenchen', to_date('9/14/2016','MM/DD/YYYY'), 712);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (368, 'Mr. AGs-Event', 'Grenchen', to_date('9/2/2016','MM/DD/YYYY'), 563);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (369, 'Maxaprofit-Event', 'Grenchen', to_date('1/1/2016','MM/DD/YYYY'), 352);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (370, 'White Coffee P-Event', 'Grenchen', to_date('1/9/2014','MM/DD/YYYY'), 312);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (371, 'Market Basket-Event', 'Grenchen', to_date('1/3/2014','MM/DD/YYYY'), 265);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (372, 'Shabby Chic-Event', 'Obernau', to_date('10/29/2016','MM/DD/YYYY'), 641);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (373, 'Wells + Wade-Event', 'Zürich', to_date('11/23/2017','MM/DD/YYYY'), 378);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (374, 'Steak and Ale-Event', 'Zürich', to_date('11/24/2014','MM/DD/YYYY'), 256);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (375, 'HouseWorks!-Event', 'Zürich', to_date('9/4/2014','MM/DD/YYYY'), 822);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (376, 'Nickerson Farm-Event', 'Grenchen', to_date('5/2/2014','MM/DD/YYYY'), 586);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (377, 'Prestiga-Biz-Event', 'Bern', to_date('4/7/2014','MM/DD/YYYY'), 369);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (378, 'Whitlocks Auto-Event', 'Lausanne', to_date('6/30/2016','MM/DD/YYYY'), 363);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (379, 'K+G Distributo-Event', 'Lausanne', to_date('7/30/2014','MM/DD/YYYY'), 402);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (380, 'Ejecta-Event', 'Genf', to_date('12/20/2016','MM/DD/YYYY'), 273);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (381, 'Richman Brothe-Event', 'Luzern', to_date('6/28/2017','MM/DD/YYYY'), 878);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (382, 'Price Club-Event', 'Grenchen', to_date('5/4/2015','MM/DD/YYYY'), 873);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (383, 'Greenwich IGA-Event', 'St. Gallen', to_date('7/19/2015','MM/DD/YYYY'), 765);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (384, 'Envirotecture -Event', 'Engollon', to_date('3/9/2016','MM/DD/YYYY'), 795);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (385, 'Netobill-Event', 'Althäusern', to_date('3/16/2017','MM/DD/YYYY'), 570);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (386, 'The Goose and -Event', 'Gross', to_date('3/27/2015','MM/DD/YYYY'), 438);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (387, 'Frame Scene-Event', 'Minusio', to_date('2/18/2017','MM/DD/YYYY'), 256);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (388, 'Gamble-Skogmo-Event', 'Hinterrhein', to_date('12/8/2015','MM/DD/YYYY'), 561);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (389, 'Henrys Hambur-Event', 'Grenchen', to_date('12/21/2014','MM/DD/YYYY'), 578);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (390, 'Hughes + Hatch-Event', 'Grenchen', to_date('8/31/2015','MM/DD/YYYY'), 538);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (391, 'Britling Cafet-Event', 'Grenchen', to_date('7/5/2014','MM/DD/YYYY'), 322);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (392, 'Chase Pitkin-Event', 'Grenchen', to_date('4/18/2017','MM/DD/YYYY'), 470);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (393, 'Second Time Ar-Event', 'Grenchen', to_date('3/28/2015','MM/DD/YYYY'), 274);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (394, 'Cut Rite Lawn -Event', 'Grenchen', to_date('3/25/2015','MM/DD/YYYY'), 438);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (395, 'Magna Consulti-Event', 'Grenchen', to_date('1/25/2014','MM/DD/YYYY'), 484);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (396, 'Blockbuster Mu-Event', 'Grenchen', to_date('7/28/2016','MM/DD/YYYY'), 485);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (397, 'Record + Tape -Event', 'Grenchen', to_date('4/21/2015','MM/DD/YYYY'), 651);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (398, 'Food Barn-Event', 'Grenchen', to_date('5/21/2015','MM/DD/YYYY'), 455);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (399, 'Universal Desi-Event', 'Grenchen', to_date('9/12/2016','MM/DD/YYYY'), 204);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (400, 'Carrols Restau-Event', 'Grenchen', to_date('3/2/2017','MM/DD/YYYY'), 805);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (401, 'Chi-Chis-Event', 'Grenchen', to_date('7/18/2014','MM/DD/YYYY'), 233);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (402, 'Hollywood Vide-Event', 'Grenchen', to_date('3/8/2016','MM/DD/YYYY'), 275);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (403, 'Sistemos-Event', 'Niedergösgen', to_date('1/3/2014','MM/DD/YYYY'), 699);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (404, 'Schucks Auto S-Event', 'Corbeyrier', to_date('2/12/2014','MM/DD/YYYY'), 685);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (405, 'Integra Design-Event', 'Zauggenried', to_date('7/4/2014','MM/DD/YYYY'), 874);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (406, 'Rinks-Event', 'Eriswil', to_date('6/1/2015','MM/DD/YYYY'), 393);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (407, 'Good Guys-Event', 'Ebertswil', to_date('12/25/2016','MM/DD/YYYY'), 297);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (408, 'Grodins-Event', 'Grenchen', to_date('11/15/2014','MM/DD/YYYY'), 519);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (409, 'Canal Villere-Event', 'Grenchen', to_date('11/25/2016','MM/DD/YYYY'), 535);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (410, 'Mission Realty-Event', 'Grenchen', to_date('2/17/2015','MM/DD/YYYY'), 788);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (411, 'W. Bell + Co.-Event', 'Grenchen', to_date('8/11/2017','MM/DD/YYYY'), 812);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (412, 'Hugh M. Woods-Event', 'Grenchen', to_date('2/22/2015','MM/DD/YYYY'), 419);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (413, 'Independent In-Event', 'Grenchen', to_date('8/2/2016','MM/DD/YYYY'), 511);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (414, 'Omni Tech Solu-Event', 'Grenchen', to_date('2/2/2014','MM/DD/YYYY'), 408);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (415, 'Holly Tree Inn-Event', 'Grenchen', to_date('2/9/2014','MM/DD/YYYY'), 778);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (416, 'Packer-Event', 'Grenchen', to_date('8/14/2017','MM/DD/YYYY'), 854);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (417, 'Super Saver Fo-Event', 'Grenchen', to_date('8/13/2016','MM/DD/YYYY'), 608);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (418, 'Griffs Hambur-Event', 'Grenchen', to_date('9/26/2014','MM/DD/YYYY'), 440);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (419, 'Playworld-Event', 'Grenchen', to_date('10/11/2017','MM/DD/YYYY'), 489);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (420, 'Disc Jockey-Event', 'Grenchen', to_date('9/22/2014','MM/DD/YYYY'), 727);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (421, 'Helping Hand-Event', 'Grenchen', to_date('12/3/2016','MM/DD/YYYY'), 747);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (422, 'Edge Garden Se-Event', 'Grenchen', to_date('9/24/2015','MM/DD/YYYY'), 373);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (423, 'Independent In-Event', 'Grenchen', to_date('2/6/2016','MM/DD/YYYY'), 693);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (424, 'One-Up Realty-Event', 'Grenchen', to_date('11/8/2015','MM/DD/YYYY'), 351);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (425, 'Matrix Archite-Event', 'Grenchen', to_date('7/16/2015','MM/DD/YYYY'), 547);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (426, 'Zany Brainy-Event', 'Zürich', to_date('7/10/2014','MM/DD/YYYY'), 713);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (427, 'Pioneer Chicke-Event', 'Grenchen', to_date('9/13/2014','MM/DD/YYYY'), 430);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (428, 'Fedco-Event', 'Grenchen', to_date('7/30/2014','MM/DD/YYYY'), 537);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (429, 'Mr. AGs-Event', 'Grenchen', to_date('6/19/2015','MM/DD/YYYY'), 819);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (430, 'Rinks-Event', 'Grenchen', to_date('6/14/2014','MM/DD/YYYY'), 356);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (431, 'Ellmans Catal-Event', 'Grenchen', to_date('5/11/2014','MM/DD/YYYY'), 296);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (432, 'Soul Sounds Un-Event', 'Grenchen', to_date('2/27/2016','MM/DD/YYYY'), 489);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (433, 'Sistemos-Event', 'Grenchen', to_date('10/20/2015','MM/DD/YYYY'), 377);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (434, 'Mervyns-Event', 'Grenchen', to_date('4/17/2016','MM/DD/YYYY'), 849);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (435, 'Sports Unlimit-Event', 'Grenchen', to_date('4/30/2015','MM/DD/YYYY'), 743);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (436, 'Mikro Designs-Event', 'Grenchen', to_date('8/13/2015','MM/DD/YYYY'), 233);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (437, 'Prospa-Pal-Event', 'Grenchen', to_date('9/6/2016','MM/DD/YYYY'), 637);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (438, 'Choices-Event', 'Grenchen', to_date('1/4/2015','MM/DD/YYYY'), 720);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (439, 'World of Fun-Event', 'Grenchen', to_date('7/17/2014','MM/DD/YYYY'), 459);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (440, 'Adray-Event', 'Grenchen', to_date('5/26/2017','MM/DD/YYYY'), 902);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (441, 'Mikrotechnic-Event', 'Grenchen', to_date('10/22/2014','MM/DD/YYYY'), 744);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (442, 'Shoe Pavilion-Event', 'Gundetswil', to_date('7/23/2014','MM/DD/YYYY'), 427);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (443, 'Polk Brothers-Event', 'Ausser Dinhard', to_date('11/14/2016','MM/DD/YYYY'), 850);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (444, 'Freedom Map-Event', 'Berzona', to_date('5/16/2014','MM/DD/YYYY'), 418);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (445, 'The Happy Bear-Event', 'Zürich', to_date('3/25/2016','MM/DD/YYYY'), 803);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (446, 'Highland Appli-Event', 'Zürich', to_date('8/26/2015','MM/DD/YYYY'), 422);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (447, 'Office Warehou-Event', 'Zürich', to_date('12/7/2016','MM/DD/YYYY'), 615);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (448, 'Childrens Barg-Event', 'Bern', to_date('7/20/2016','MM/DD/YYYY'), 345);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (449, 'J. B. Van Sciv-Event', 'Grenchen', to_date('3/31/2014','MM/DD/YYYY'), 286);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (450, 'Leos Stereo-Event', 'Lausanne', to_date('7/25/2015','MM/DD/YYYY'), 405);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (451, 'Maxiserve-Event', 'Lausanne', to_date('9/12/2017','MM/DD/YYYY'), 224);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (452, 'Paper Cutter-Event', 'Genf', to_date('8/8/2016','MM/DD/YYYY'), 382);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (453, 'Angels-Event', 'Grenchen', to_date('5/2/2016','MM/DD/YYYY'), 328);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (454, 'Strongbod-Event', 'Biel/Bienne', to_date('7/20/2015','MM/DD/YYYY'), 643);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (455, 'Magna Wealth-Event', 'St. Gallen', to_date('6/22/2014','MM/DD/YYYY'), 731);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (456, 'Warshals-Event', 'Arbaz', to_date('8/29/2014','MM/DD/YYYY'), 504);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (457, 'Total Network -Event', 'La Tour-de-Peilz', to_date('8/7/2014','MM/DD/YYYY'), 875);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (458, 'Frame Scene-Event', 'Schönenwerd', to_date('12/17/2014','MM/DD/YYYY'), 444);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (459, 'Lifes Gold-Event', 'Oberbözberg', to_date('7/4/2016','MM/DD/YYYY'), 749);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (460, 'New World-Event', 'Caslano', to_date('12/21/2013','MM/DD/YYYY'), 685);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (461, 'Life Map Plann-Event', 'St-Léonard', to_date('9/1/2015','MM/DD/YYYY'), 321);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (462, 'Dave Cooks-Event', 'Zürich', to_date('3/26/2014','MM/DD/YYYY'), 355);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (463, 'Good Guys-Event', 'Basel', to_date('8/10/2017','MM/DD/YYYY'), 201);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (464, 'Terra Nova Gar-Event', 'Cadempino', to_date('10/6/2017','MM/DD/YYYY'), 392);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (465, 'DGS HomeSource-Event', 'Mézières', to_date('11/29/2015','MM/DD/YYYY'), 800);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (466, 'Omni Superstor-Event', 'Zürich', to_date('3/28/2016','MM/DD/YYYY'), 311);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (467, 'Mikrotechnic-Event', 'Grenchen', to_date('8/22/2016','MM/DD/YYYY'), 778);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (468, 'Manu Connectio-Event', 'Zürich', to_date('12/22/2016','MM/DD/YYYY'), 822);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (469, 'Steve + Barry-Event', 'Bern', to_date('10/20/2014','MM/DD/YYYY'), 804);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (470, 'J. Brannam-Event', 'Bern', to_date('9/12/2014','MM/DD/YYYY'), 235);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (471, 'Chi-Chis-Event', 'Lausanne', to_date('8/11/2015','MM/DD/YYYY'), 227);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (472, 'Glicks Furnitu-Event', 'Lausanne', to_date('3/27/2015','MM/DD/YYYY'), 499);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (473, 'Creative Wealt-Event', 'Genf', to_date('7/26/2014','MM/DD/YYYY'), 639);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (474, 'Cuppys Coffee-Event', 'Luzern', to_date('11/27/2015','MM/DD/YYYY'), 291);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (475, 'Rinks-Event', 'Biel/Bienne', to_date('4/10/2014','MM/DD/YYYY'), 206);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (476, 'Integra Invest-Event', 'St. Gallen', to_date('5/6/2017','MM/DD/YYYY'), 720);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (477, 'Marianne-Event', 'Manno', to_date('7/30/2015','MM/DD/YYYY'), 393);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (478, 'Lums-Event', 'Hasel', to_date('11/16/2014','MM/DD/YYYY'), 408);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (479, 'Monsource-Event', 'Hetzlige', to_date('3/3/2015','MM/DD/YYYY'), 461);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (480, 'Monsource-Event', 'Posieux', to_date('3/21/2016','MM/DD/YYYY'), 632);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (481, 'Leonard Krower-Event', 'Les Rites', to_date('11/10/2017','MM/DD/YYYY'), 777);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (482, 'Rinks-Event', 'Grenchen', to_date('2/23/2017','MM/DD/YYYY'), 888);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (483, 'VitaGrey-Event', 'Unterniesenberg', to_date('7/10/2014','MM/DD/YYYY'), 346);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (484, 'Mr. Ds IGA-Event', 'Zürich', to_date('6/12/2015','MM/DD/YYYY'), 527);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (485, 'Forum Cafeteri-Event', 'Zürich', to_date('6/25/2014','MM/DD/YYYY'), 700);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (486, 'Sambos-Event', 'Zürich', to_date('9/1/2016','MM/DD/YYYY'), 791);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (487, 'Xray Eye + Vis-Event', 'Bern', to_date('7/21/2014','MM/DD/YYYY'), 718);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (488, 'Golden Dawn-Event', 'Bern', to_date('4/18/2017','MM/DD/YYYY'), 798);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (489, 'Lifes Gold-Event', 'Lausanne', to_date('5/12/2015','MM/DD/YYYY'), 493);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (490, 'Miller + Rhoad-Event', 'Lausanne', to_date('7/21/2015','MM/DD/YYYY'), 773);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (491, 'Jacobs-Event', 'Grenchen', to_date('6/23/2016','MM/DD/YYYY'), 359);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (492, 'Lawnscape Gard-Event', 'Luzern', to_date('7/22/2017','MM/DD/YYYY'), 241);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (493, 'Century House-Event', 'Biel/Bienne', to_date('7/12/2015','MM/DD/YYYY'), 328);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (494, 'Omni Realty-Event', 'Grenchen', to_date('3/20/2014','MM/DD/YYYY'), 465);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (495, 'Laughners Caf-Event', 'Granges-de-Vesin', to_date('11/3/2015','MM/DD/YYYY'), 634);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (496, 'Asian Junction-Event', 'St. Gallen', to_date('3/1/2015','MM/DD/YYYY'), 398);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (497, 'Formula Gray-Event', 'Gfill', to_date('6/6/2014','MM/DD/YYYY'), 850);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (498, 'Asian Plan-Event', 'Grenchen', to_date('2/21/2017','MM/DD/YYYY'), 277);
INSERT INTO anlass (anlaid, bezeichner, ort, datum, orgid) VALUES (499, 'The Polka Dot -Event', 'Mohren', to_date('4/7/2014','MM/DD/YYYY'), 361);


COMMIT;

ALTER SESSION SET CURRENT_SCHEMA = sys;